# CTCLoss Example

In [47]:
%reload_ext autoreload
%autoreload 2
%matplotlib inline

In [48]:
from fastai.basics import *

In [68]:
T = 50     # Input sequence length
C = 20     # Number of classes (including blank)
BS = 16    # Batch size
S = 30     # Target sequence length of longest target in batch
S_min = 10 # Minimum target length, for demonstration purposes

In [72]:
# Initialize random batch of input vectors, for size = (T, BS, C)
x = torch.randn(T, BS, C)
x.shape, x

(torch.Size([50, 16, 20]),
 tensor([[[ 0.1912, -0.6004,  1.0019,  ...,  1.0453,  2.6901,  0.8102],
          [ 0.5493,  0.1792, -1.3953,  ...,  0.1747,  0.2433, -0.7268],
          [ 0.1476,  0.7673,  0.4982,  ...,  1.8686, -0.8635, -0.4811],
          ...,
          [ 0.3200, -0.0528, -0.3026,  ..., -0.9871,  2.2112,  0.2748],
          [-0.6888, -0.4313, -0.0318,  ..., -1.4563, -0.1316, -0.1610],
          [ 1.0971, -1.3328, -0.8226,  ...,  0.2913, -0.7005, -1.0957]],
 
         [[-1.4081, -0.2913,  0.1484,  ...,  0.8799,  0.3579,  0.1327],
          [ 0.3080,  0.4841, -0.8652,  ..., -0.6387, -0.9820,  0.5723],
          [ 0.7677, -0.3993, -1.2052,  ...,  1.1702, -0.0673, -0.0919],
          ...,
          [ 0.0077,  0.7767,  0.3871,  ..., -0.0483, -1.1508,  0.0665],
          [-0.8755,  1.4541,  0.6552,  ..., -0.9584,  0.7447,  0.7366],
          [-0.7158,  0.4206,  0.0264,  ...,  0.7446, -1.1406, -0.8526]],
 
         [[ 1.0986,  0.3699, -0.2590,  ..., -0.6158, -0.3636, -0.9504],
 

In [73]:
# Initialize random batch of targets (0 = blank, 1:C = classes)
y = torch.randint(low=1, high=C, size=(BS, S), dtype=torch.long)
y.shape, y

(torch.Size([16, 30]),
 tensor([[ 2, 11, 16, 13, 13, 18, 19,  7, 13,  7, 14, 19, 11,  8,  1,  2, 19,  3,
           8, 18, 15, 19, 18, 14, 10, 11,  3,  1,  8, 14],
         [12, 19, 13,  7, 13,  2,  6,  2, 19,  6, 18,  8, 19, 19,  1, 16,  8, 19,
          13,  1,  3, 14, 13, 18,  4,  4,  8, 12,  3,  8],
         [ 3,  1,  5, 14,  3, 13, 15,  9, 10, 14, 12, 17,  3, 18,  1, 10,  6, 17,
          17,  7, 12, 11, 13,  7,  3, 14, 10, 16, 16,  8],
         [ 3, 14,  6,  9, 15,  2, 12, 14, 13, 14, 14,  6, 18,  5,  3,  4,  5,  9,
          18,  7, 18,  1,  1, 17,  7,  9, 11, 10, 10,  3],
         [ 1, 18, 18, 14,  5,  6,  1,  8, 10,  3, 10, 12,  8,  4,  5, 13, 14,  1,
          18, 14, 12, 12,  1,  3, 14, 17,  8, 15, 17,  8],
         [12,  3,  7, 13, 13,  5,  1, 13,  6,  3,  5, 14, 11, 16,  7, 11, 17, 19,
           7, 19, 12,  8, 19,  7, 19,  7,  5, 15, 17,  8],
         [ 2,  7, 17, 18, 11,  9, 11,  6,  5,  9, 18,  5, 12,  4,  1, 18, 16, 19,
          15,  4, 12, 19, 17, 19,  7, 12, 15,  3,

In [77]:
x_lengths = torch.full(size=(N,), fill_value=T, dtype=torch.long)
y_lengths = torch.randint(low=S_min, high=S, size=(BS,), dtype=torch.long)
x_lengths.shape, x_lengths, x_lengths.shape, y_lengths

(torch.Size([16]),
 tensor([50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50]),
 torch.Size([16]),
 tensor([26, 12, 17, 17, 28, 24, 27, 20, 17, 13, 23, 18, 16, 10, 16, 25]))

In [65]:
ctc_loss = nn.CTCLoss()

In [79]:
loss = ctc_loss(x, y, x_lengths, y_lengths)
loss

tensor(-3.3712)